#version 450

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1)
layout( binding =0 ) buffer Raw{
	float src[];
};
layout( binding = 1)  buffer VolumeTest{
	uint dst[];
};
layout( binding = 2 ) uniform IsoValue{
	float isovalue;
};

uint flatten_index(uvec3 dim){
	return 0;
}

uvec3 idx2pos(uint id, uvec3 dim){
	uvec3 pos;

	return pos;
}

uint pos2idx(uvec3 pos, uvec3 dim){
	uint idx = pos.x + pos.y * dim.x + pos.z * dim.x * dim.y;
	return idx;
}

void main() {
	uvec3 id = gl_GlobalInvocationID;
	uvec3 dim = gl_NumWorkGroups;
	float i = isovalue;
	float value[8] = {
		
	};
	uint ctest[8];

	ctest[0] = uint(              )
}