#version 450
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout(std430, binding =0 ) readonly buffer Raw{
	float raw[];
};
layout(std430, binding = 1)  writeonly buffer TriCount{
	uint tri_count[];
};

layout(std430, binding = 2) writeonly buffer CellType{
	uint Cell_Type[];
};

layout( binding = 3 ) uniform IsoValue{
	float isovalue;
};

layout(std430,binding = 4) readonly buffer Dim{
	uvec3 vdim;
};

const uint nr_triangles[256] = { 0,1,1,2,1,2,2,3,
								 1,2,2,3,2,3,3,2,
								 1,2,2,3,2,3,3,4,
								 2,3,3,4,3,4,4,3,
								 1,2,2,3,2,3,3,4,
								 2,3,3,4,3,4,4,3,
								 2,3,3,2,3,4,4,3,
								 3,4,4,3,4,5,5,2,
								 1,2,2,3,2,3,3,4,
								 2,3,3,4,3,4,4,3,
								 2,3,3,4,3,4,4,5,
								 3,4,4,5,4,5,5,4,
								 2,3,3,4,3,4,2,3,
								 3,4,4,5,4,5,3,2,
								 3,4,4,3,4,5,3,2,
								 4,5,5,4,5,2,4,1,
								 1,2,2,3,2,3,3,4,
								 2,3,3,4,3,4,4,3,
								 2,3,3,4,3,4,4,5,
								 3,2,4,3,4,3,5,2,
								 2,3,3,4,3,4,4,5,
								 3,4,4,5,4,5,5,4,
								 3,4,4,3,4,5,5,4,
								 4,3,5,2,5,4,2,1,
								 2,3,3,4,3,4,4,5,
								 3,4,4,5,2,3,3,2,
								 3,4,4,5,4,5,5,2,
								 4,3,5,4,3,2,4,1,
								 3,4,4,5,4,5,3,4,
								 4,5,5,2,3,4,2,1,
								 2,3,3,2,3,4,2,1,
								 3,2,4,1,2,1,1,0 };

uint pos2idx(uvec3 pos, uvec3 dim){
	return pos.x + dim.x*(pos.y + pos.z*dim.y);
}

void main() {
	uvec3 pos = gl_GlobalInvocationID.xyz;
	uvec3 dim = vdim - 2;//gl_NumWorkGroups.xyz;
	dim += 2; 
	uint id = pos2idx(pos, dim);
	uint cell_type = (uint(raw[ id ] > isovalue) |
			  uint( raw[ pos2idx( pos + uvec3(1,0,0), dim) ] > isovalue ) << 1 | 
			  uint( raw[ pos2idx( pos + uvec3(1,1,0), dim) ] > isovalue ) << 2 |
			  uint( raw[ pos2idx( pos + uvec3(0,1,0), dim) ] > isovalue ) << 3 |
			  uint( raw[ pos2idx( pos + uvec3(0,0,1), dim) ] > isovalue ) << 4 |
			  uint( raw[ pos2idx( pos + uvec3(1,0,1), dim) ] > isovalue ) << 5 |
			  uint( raw[ pos2idx( pos + uvec3(1,1,1), dim) ] > isovalue ) << 6 |
			  uint( raw[ pos2idx( pos + uvec3(0,1,1), dim) ] > isovalue ) << 7);
	id = pos2idx(pos, dim-2);
	tri_count[id] = nr_triangles[cell_type];
	Cell_Type[id] = cell_type;
}