#version 450
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout( binding =0 ) buffer Raw{
	uint raw[];
};

layout( binding=1 ) buffer EdgeTest{
	uvec3 edge_test[];
};

layout( binding=2 ) uniform IsoValue{
	float isovalue;
};


/*
           	  v7 ______________v6			  
			   /|		 	  /|
			  / |			 / |
			 /  |		    /  |
		    /___|________v5/   |
		   |    |         |    |
		   |  v3|_________|____|v2
		   |   /		  |	  /	
		  e2 e1			  |  /		
		   | /			  | /
		   |______e0______|/
		  v0			  v1
*/			

uint pos2idx(uvec3 pos, uvec3 dim){
	uint idx = pos.x + pos.y * dim.x + pos.z * dim.x * dim.y;
	return idx;
}

void main() {
	/**
	on each P=(x,y,z), x,y,z in N
	has 3 edge direction to x, y, z axis
	*/
	uvec3 pos = gl_GlobalInvocationID.xyz;
	uvec3 dim = gl_NumWorkGroups.xyz;
	uint id = pos2idx(pos, dim);
	bool o = raw[id] < isovalue;
	uvec3 test;
	test.x = uint( o ^^ ( raw[ pos2idx( pos + uvec3(1,0,0), dim )] > isovalue ) );
	test.y = uint( o ^^ ( raw[ pos2idx( pos + uvec3(0,1,0), dim )] > isovalue ) );
	test.z = uint( o ^^ ( raw[ pos2idx( pos + uvec3(0,0,1), dim )] > isovalue ) );

	edge_test[id] = test;
}