#version 450
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout( binding =0 ) buffer VolumeTest{
	uint volume_test[];
};

layout( binding=1 ) buffer EdgeTest{
	uint edge_test[];
};


/*
			   v7-----e10-----v6
           	   /			  /|
			  /	|			 / |
			e11	e7			e9 e6
			/	|		   /   |
		   |--------------|v5  |
		   |  v3|_ _ _ _ _| _ _|v2
		   |   /		  |	  /	
		  e2 e1			  |  /		
		   | /			  | /
		   |______e0______|/
		  v0			  v1
*/			


void main() {
	/**
	on each P=(x,y,z), x,y,z in N
	has 3 edge direction to x, y, z axis
	*/
	uvec3 gid = gl_GlobalInvocationID.xyz;
	uvec3 dim = gl_NumWorkGroups.xyz;
	uint idx = gid.x + gid.y * dim.x  + gid.z * dim.x * dim.y;
	uint v = volume_test[idx];
	
	edge_test[3*idx] =  (v^volume_test[idx+1]) ;
	edge_test[3*idx+1] = (v^volume_test[idx+gid.y*dim.x]) ;
	edge_test[3*idx+2] = (v^volume_test[idx+gid.z*dim.y*dim.x]); 
}