#version 450
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0) buffer Source{
	uvec4 dst[];
};

layout(binding = 1) buffer GroupSum{
	uint group_sum[];
};

void main(){
	uint id = gl_GlobalInvocationID.x;
	uint grp_id = gl_WorkGroupID.x;
	uint sz_grp = gl_NumWorkGroups.x;
	uvec4 data = dst[id];
	
	if(grp_id != 0){
		data += uvec4(group_sum[grp_id]);
		//dst[id] = data;
		//dst[id] = uvec4(1);//data;
	}
}