#version 450
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1)

layout( binding =0 ) buffer Raw{
	float volume[];
};

layout( binding = 1)  buffer VolumeTest{
	bool vtest[];
};

layout( binding = 2 ) uniform IsoValue{
	float isovalue[];
};


void main() {
	uvec3 gid = gl_GlobalInvocationID.xyz;
	uvec3 dim = gl_NumWorkGroups.xyz;
	uint idx = gid.x + gid.y * dim.x  + gid.z * dim.x * dim.y;

	//if(idx >= sz_workitems)
		//return ;

	vtest[idx] = ( volume[idx]  > isovalue[0]) ? true: false;
}